<a href="https://colab.research.google.com/github/HoangShiya/HUET/blob/main/numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Bài 1 - Ma trận**: Trong toán học, ma trận (matrix) là một mảng 2 chiều chứa số hoặc các đối tượng toán học khác. Một cách tổng quát ma trận A có m hàng và n cột chứa các số thực, ký hiệu là A ∈ $R^{m*n}$ hay $A_{m*n}$ hay A = ($a_{i*j}$)$_{m*n}$

A = (\begin{array}{ccc}
\text{$A_{1,1}$}&\text{$A_{1,2}$}&\text{...}&\text{$A_{1,n}$}\\
\text{$A_{2,1}$}&\text{$A_{2,2}$}&\text{...}&\text{$A_{2,n}$}\\
\text{...}&\text{...}&\text{...}&\text{...}\\
\text{$A_{1,1}$}&\text{$A_{1,2}$}&\text{...}&\text{$A_{1,n}$}
\end{array})

Sử dụng thư viện NumPy, hãy tạo ra một ma trận A ∈ $R^{7*5}$, gía trị các phần tử của ma trận được sinh ra ngẫu nhiên. Kết quả xuất ra màn hình.

In [ ]:
'''
*
* Sử dụng thư viện sau:
*
* numpy: Làm việc, xử lí trên dữ liệu Dataframe
*
'''
import pandas 


'''
*
* Cú pháp np.random.rand (d0, d1, …, dn)
*
* Chức năng này của mô-đun ngẫu nhiên được sử dụng để tạo ra các số hoặc giá trị ngẫu nhiên trong một hình dạng nhất định.
*
* Cú pháp numpy.set_printoptions(precision=None, threshold=None, edgeitems=None, linewidth=None, suppress=None, nanstr=None, infstr=None, formatter=None, sign=None, floatmode=None, *, legacy=None)
* => Chức này của mô-đun Đặt các tùy chọn in. Các tùy chọn này xác định cách số dấu phẩy động, mảng và các đối tượng NumPy khác được hiển thị.
*
'''
np.set_printoptions(precision=1, suppress=True)

matrix = np.random.rand(7, 5)


# Xuất giá trị các phần tử của ma trận ra khỏi màn hình
print(matrix)

[[0.1 0.9 0.1 0.3 0.1]
 [0.1 0.2 0.2 0.  0.1]
 [1.  0.9 0.5 0.2 0.3]
 [0.2 0.2 0.  0.1 0.8]
 [0.8 0.4 0.7 0.4 0.8]
 [0.7 0.7 0.7 0.1 0.8]
 [0.9 1.  0.1 0.8 0.8]]


**Bài 2 - Ma trận không (zero matrix)**: Ma trận $A_{m*n}$ được gọi là ma trận không khi $a_{i,j}$ = 0,∀*i,j*.\
Sử dụng thư viện Numpy, hãy tạo một ma trận 0 - $A_{6*7}$. Gợi ý: sử dụng hàm numpy.zeros((m,n)).\
Kết quả xuất ra màn hình.

In [ ]:
'''
*
* Sử dụng thư viện sau:
*
* numpy: Tính toán số học, vector, ma trận.
*
'''
import numpy as np


'''
*
* Cú pháp numpy.zeros(shape, dtype = None, order = 'C')
*
* Chức năng hàm trả về một mảng mới có hình dạng và kiểu đã cho, với các số không.
*
'''
matrix = np.zeros((6, 7))


# Xuất giá trị các phần tử của ma trận 0 - A(6*7) ra khỏi màn hình
print(0 - matrix)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


**Bài 3 - Ma trận vuông:** Là ma trận có số hàng và số cột bằng nhau. Sử dụng thư viện NumPy, hãy tạo ra một ma trận A ∈ $R^{7*7}$, giá trị các phần tử của ma trận được sinh ngẫu nhiên. Kết quả xuất ra màn hình

In [ ]:
'''
*
* Sử dụng thư viện sau:
*
* numpy: Tính toán số học, vector, ma trận.
*
'''
import numpy as np


'''
*
* Cú pháp np.random.rand (d0, d1, …, dn)
*
* Chức năng này của mô-đun ngẫu nhiên được sử dụng để tạo ra các số hoặc giá trị ngẫu nhiên trong một hình dạng nhất định.
*
* Cú pháp numpy.set_printoptions(precision=None, threshold=None, edgeitems=None, linewidth=None, suppress=None, nanstr=None, infstr=None, formatter=None, sign=None, floatmode=None, *, legacy=None)
* => Chức này của mô-đun Đặt các tùy chọn in. Các tùy chọn này xác định cách số dấu phẩy động, mảng và các đối tượng NumPy khác được hiển thị.
*
'''
np.set_printoptions(precision=1, suppress=True)

matrix = np.random.rand(7, 7)


# Xuất giá trị các phần tử của ma trận ra khỏi màn hình
print(matrix)

[[0.2 0.8 0.8 0.8 0.9 1.  0.8]
 [0.5 0.5 0.2 0.8 0.2 0.6 0.3]
 [0.3 0.3 0.7 0.9 0.3 0.1 1. ]
 [0.6 0.6 0.3 0.8 0.4 0.7 0.9]
 [0.8 0.5 0.8 0.3 0.4 0.6 0.9]
 [0.8 0.9 0.8 0.7 0.5 0.4 0.8]
 [0.8 0.6 0.4 0.  0.9 0.3 0.6]]


**Bài 4 - Ma trận chéo (diagonal matrix):** Ma trận vuông có các phần tử trên đường chéo *$a_{i,j}$* ≠ 0 trong khi các phần tử còn lại *$a_{i,j}$* = 0, ∀i ≠ j. \\
Sử dụng thư viện NumPy, hãy tạo một ma trận chéo *$A_{6*6}$* với phần tử nằm trên đường chéo có giá trị là 15. Gợi ý: sử dụng kết hợp hàm numpy.zeros() và numpy.fill_digonal().\
Kết quả xuất ra màn hình. 

In [ ]:
'''
*
* Sử dụng thư viện sau:
*
* numpy: Tính toán số học, vector, ma trận.
*
'''
import numpy as np


'''
*
* 1) Cú pháp numpy.zeros(shape, dtype = None, order = 'C')
* => Chức năng hàm trả về một mảng mới có hình dạng và kiểu đã cho, với các số không.
*
* 2) Cú pháp numpy.fill_diagonal(a, val, wrap=False)
* =>  Chức năng hàm điền vào đường chéo chính của mảng bất kỳ chiều nào đã cho.
*
'''
matrix = np.zeros((6,6), int)
np.fill_diagonal(matrix, 15)


# Xuất giá trị các phần tử của ma trận ra khỏi màn hình
print(matrix)

[[15  0  0  0  0  0]
 [ 0 15  0  0  0  0]
 [ 0  0 15  0  0  0]
 [ 0  0  0 15  0  0]
 [ 0  0  0  0 15  0]
 [ 0  0  0  0  0 15]]


**Bài 5-Ma trận tam giác trên (upper triangular matrix)**: Ma trận vuông $A_{n*n}$ được gọi là ma trận tam giác trên nếu các phần tử nằm trên đường chéo đều khác 0 và các phần tử nằm dưới đường chéo đều bằng 0. \\
Sử dụng thư viện NumPy, hãy tạo một ma trận tam giác trên $A_{8*8}$. Gợi ý: sử dụng hàm numpy.triu(). Kết quả xuất ra màn hình

In [ ]:
'''
*
* Sử dụng thư viện sau:
*
* numpy: Tính toán số học, vector, ma trận.
*
'''
import numpy as np


'''
*
* Cú pháp numpy.set_printoptions(precision=None, threshold=None, edgeitems=None, linewidth=None, suppress=None, nanstr=None, infstr=None, formatter=None, sign=None, floatmode=None, *, legacy=None)
* => Chức này của mô-đun Đặt các tùy chọn in. Các tùy chọn này xác định cách số dấu phẩy động, mảng và các đối tượng NumPy khác được hiển thị.
*
* Cú pháp np.triu(m, k=0)
* => Chức năng này của mô-đun trả về bản sao của một mảng với các phần tử bên dưới đường chéo thứ k được làm bằng 0. Đối với mảng có ndim vượt quá 2, triu sẽ áp dụng cho hai trục cuối cùng.
*
* Cú pháp np.random.rand (d0, d1, …, dn)
* => Chức năng này của mô-đun ngẫu nhiên được sử dụng để tạo ra các số hoặc giá trị ngẫu nhiên trong một hình dạng nhất định.
*
'''
np.set_printoptions(precision=1, suppress=True)

matrix = np.triu(np.random.rand(8, 8), -1)


# Xuất giá trị các phần tử của ma trận ra khỏi màn hình
print(matrix)

[[0.7 0.  0.7 1.  0.4 0.1 0.4 0.3]
 [0.9 0.  0.5 0.3 0.2 0.2 0.8 0.2]
 [0.  0.5 0.2 0.2 0.4 0.2 0.1 0.2]
 [0.  0.  0.3 0.5 0.4 0.3 0.7 0.6]
 [0.  0.  0.  0.1 0.8 0.4 0.7 0.3]
 [0.  0.  0.  0.  0.9 0.2 0.7 0.5]
 [0.  0.  0.  0.  0.  0.6 0.2 0.6]
 [0.  0.  0.  0.  0.  0.  0.7 0.8]]


**Bài 6 - Ma trận tam giác dưới (lower triangular matrix)**: Tương tự bài 5, bạn hãy xây dựng ma trận tam giác dưới. Kết quả xuất ra màn hình.

In [ ]:
'''
*
* Sử dụng thư viện sau:
*
* numpy: Tính toán số học, vector, ma trận.
*
'''
import numpy as np


'''
*
* Cú pháp numpy.set_printoptions(precision=None, threshold=None, edgeitems=None, linewidth=None, suppress=None, nanstr=None, infstr=None, formatter=None, sign=None, floatmode=None, *, legacy=None)
* => Chức này của mô-đun Đặt các tùy chọn in. Các tùy chọn này xác định cách số dấu phẩy động, mảng và các đối tượng NumPy khác được hiển thị.
*
* Cú pháp np.tril(m, k=0)
* => Chức năng này của mô-đun trả về bản sao của một mảng với các phần tử bên trên đường chéo thứ k được làm bằng 0. Đối với mảng có ndim vượt quá 2, triu sẽ áp dụng cho hai trục cuối cùng.
*
* Cú pháp np.random.rand (d0, d1, …, dn)
* => Chức năng này của mô-đun ngẫu nhiên được sử dụng để tạo ra các số hoặc giá trị ngẫu nhiên trong một hình dạng nhất định.
*
'''
np.set_printoptions(precision=1, suppress=True)

matrix = np.tril(np.random.rand(8, 8), -1)


# Xuất giá trị các phần tử của ma trận ra khỏi màn hình
print(matrix)

[[0.  0.  0.  0.  0.  0.  0.  0. ]
 [1.  0.  0.  0.  0.  0.  0.  0. ]
 [0.6 0.2 0.  0.  0.  0.  0.  0. ]
 [0.3 0.4 0.1 0.  0.  0.  0.  0. ]
 [0.2 0.2 0.9 0.4 0.  0.  0.  0. ]
 [0.9 0.9 0.4 0.5 0.6 0.  0.  0. ]
 [0.9 0.9 0.4 0.6 0.2 0.9 0.  0. ]
 [0.5 0.4 0.5 0.1 0.9 0.6 0.7 0. ]]


**Bài 7-Ma trận đơn vị (identity matrix)**: Ma trận đơn vị *$I_{n}$* có số chiều n là một ma trận vuông mà mọi phần tử trên đường chéo chính bằng 1. \\
Sử dụng thư viện NumPy, hãy tạo ra một ma trận *$I_{9}$*. Kết quả xuất ra màn hình. Gợi ý: Sử dụng hàm numpy.identity()

In [ ]:
'''
*
* Sử dụng thư viện sau:
*
* numpy: Tính toán số học, vector, ma trận.
*
'''
import numpy as np


'''
*
* Cú pháp numpy.identity(n, dtype=None, *, like=None)
* => Chức năng này của mô-đun trả về mảng nhận dạng là một mảng ma trận vuông với các giá trị 1 nằm trên đường chéo chính.
*
'''
matrix = np.identity(9)


# Xuất giá trị các phần tử của ma trận ra khỏi màn hình
print(matrix)

[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


**Bài 8-Phép toán trên ma trận**: Sử dụng thư viện NumPy để thực hiện các yêu cầu sau:

*   Phép cộng ma trận: *$A_{m*n}$* + *$B_{m*n}$* = *$C_{m*n}$*. Hãy sinh ngẫu nhiên 2 ma trận có kích thước 6x7. Thực hiện phép cộng 2 ma trận trên. Xuất giá trị các ma trận ra màn hình
*   Phép nhân vô hướng một số với ma trận: Hãy sinh ngẫu nhiên 2 ma trận có kích thước 5x8. Thực hiện nhân vô hướng 1 số được nhập từ bàn phím với ma trận này. Kết quả xuất ra màn hình
*   Phép chuyển vị ma trận: Sinh ngẫu nhiên một ma trận có kích thước 3x7. Thực hiện phép chuyển vị đối với ma trận này. Xuất các ma trận này ra màn hình.
*   Phép nhân 2 ma trận: *$A_{m*n}$*.*$B_{n*p}$* = *$C_{m*p}$*. Hãy sinh ngẫu nhiên 2 ma trận *$A_{5*7}$* và *$B_{7*3}$*, tiến hành nhân 2 ma trận này để thu được ma trận *$C_{5*3}$*. Xuất các ma trận trên ra màn hình.\
Gợi ý: Sử dụng hàm numpy.dot()
*   Ma trận khả nghịch: ma trận vuông *$A_{n*m}$* gọi là khả nghịch (hay không suy biến) nếu tồn tại một ma trận vuông *$B_{n*n}$* sao cho *A . B* = *$I_{n}$*. Khi này, B được gọi là ma trận nghịch đảo của A và ký hiệu là *$A^{-1}$*. Cho ma trận *$A_{5*5}$*, hãy tính ma trận khả nghịch của A.\
Gợi ý: Sử dụng hàm numpy.linalg.inv()







In [ ]:
'''
*
* Sử dụng thư viện sau:
*
* numpy: Tính toán số học, vector, ma trận.
*
'''
import numpy as np


'''
*
* \\MỘT SỐ CÚ PHÁP THÔNG DỤNG DÙNG ĐỂ XỬ LÍ CÁC BÀI TOÁN
*
* Cú pháp numpy.set_printoptions(precision=None, threshold=None, edgeitems=None, linewidth=None, suppress=None, nanstr=None, infstr=None, formatter=None, sign=None, floatmode=None, *, legacy=None)
* => Chức này của mô-đun Đặt các tùy chọn in. Các tùy chọn này xác định cách số dấu phẩy động, mảng và các đối tượng NumPy khác được hiển thị.
*
* Cú pháp np.random.rand (d0, d1, …, dn)
* => Chức năng này của mô-đun ngẫu nhiên được sử dụng để tạo ra các số hoặc giá trị ngẫu nhiên trong một hình dạng nhất định.
*
'''
np.set_printoptions(precision=1, suppress=True)

''' 
* \\BÀI TOÁN 1:Phép cộng ma trận:  Am∗n  +  Bm∗n  =  Cm∗n . Hãy sinh ngẫu nhiên 2 ma trận có kích thước 6x7. Thực hiện phép cộng 2 ma trận trên. Xuất giá trị các ma trận ra màn hình
* 
* Ý TƯỞNG:
* STEP1: Khởi tạo 2 biến matrix_1, matrix_2 dùng để lưu giá trị 2 ma trận
* STEP2: Sử dụng cú pháp np.random.rand(6,7) để khởi tạo 2 ma trận ngẫu nhiên kích thước (6x7)
* STEP3: Khởi tạo biến matrix_sum để lưu giá trị là kết quả của phép cộng 2 ma trận matrix_1 và matrix_2
* STEP4: Xuất giá trị matrix_sum(Phép cộng 2 ma trận) ra màn hình  
* 
'''
print("-----------------------------------------------------------------------")
print("BÀI TOÁN 1: Phép cộng ma trận:  Am∗n  +  Bm∗n  =  Cm∗n . Hãy sinh ngẫu nhiên 2 ma trận có kích thước 6x7. Thực hiện phép cộng 2 ma trận trên. Xuất giá trị các ma trận ra màn hình")
matrix_1 = np.random.rand(6, 7)
matrix_2 = np.random.rand(6, 7)

matrix_sum = matrix_1 + matrix_2

# Xuất giá trị các phần tử của ma trận ra khỏi màn hình
print(f"\nMa trận 1:\n {matrix_1}")
print(f"Ma trận 2:\n {matrix_2}")
print(f"Giá trị tổng của 2 ma trận:\n {matrix_sum}")
print("-----------------------------------------------------------------------")
print("\n")


''' 
* \\BÀI TOÁN 2:Phép nhân vô hướng một số với ma trận: Hãy sinh ngẫu nhiên 2 ma trận có kích thước 5x8. Thực hiện nhân vô hướng 1 số được nhập từ bàn phím với ma trận này. Kết quả xuất ra màn hình
* 
* Ý TƯỞNG:
* STEP1: Khởi tạo 2 biến matrix_1, matrix_2 dùng để lưu giá trị 2 ma trận
* STEP2: Sử dụng cú pháp np.random.rand(5, 8) để khởi tạo 2 ma trận ngẫu nhiên kích thước (5, 8)
* STEP3: Khởi tạo một biến lưu trữ giá trị được nhập vào từ bàn phím
* STEP3: Khởi tạo biến matrix_Multiplication_1,matrix_Multiplication_2 để lưu giá trị là kết quả của tích vô hướng 2 ma trận matrix_1 và matrix_2
* STEP4: Xuất giá trị matrix_Multiplication_1,matrix_Multiplication_2 ra màn hình  
* 
'''
print("-----------------------------------------------------------------------")
print("BÀI TOÁN 2:Phép nhân vô hướng một số với ma trận: Hãy sinh ngẫu nhiên 2 ma trận có kích thước 5x8. Thực hiện nhân vô hướng 1 số được nhập từ bàn phím với ma trận này. Kết quả xuất ra màn hình")
matrix_1 = np.random.rand(6, 7)
matrix_2 = np.random.rand(6, 7)

inp = float(input("Mời bạn nhập giá trị n: "))

matrix_Multiplication_1 = matrix_1 * inp
matrix_Multiplication_2 = matrix_2 * inp

# Xuất giá trị các phần tử của ma trận ra khỏi màn hình
print(f"\nMa trận 1:\n {matrix_1}")
print(f"Ma trận 2:\n {matrix_2}")
print(f"Giá trị tích vô hướng ma trận 1 với {inp}:\n {matrix_Multiplication_1}")
print(f"Giá trị tích vô hướng ma trận 2 với {inp}:\n {matrix_Multiplication_2}")
print("-----------------------------------------------------------------------")
print("\n")


''' 
* \\BÀI TOÁN 3:Phép chuyển vị ma trận: Sinh ngẫu nhiên một ma trận có kích thước 3x7. Thực hiện phép chuyển vị đối với ma trận này. Xuất các ma trận này ra màn hình.
* 
* Ý TƯỞNG:
* STEP1: Khởi tạo 1 biến matrix để lưu giá trị ma trận
* STEP2: Sử dụng cú pháp np.random.rand(3, 7) để khởi tạo 2 ma trận ngẫu nhiên kích thước (3, 7)
* STEP3: Khởi tạo biến matrix_transposition để lưu giá trị ma trận chuyển vị của biến matrix thông qua hàm np.transpose()
* STEP3: Xuất giá trị ma trận chuyển vị
* 
'''
print("-----------------------------------------------------------------------")
print("BÀI TOÁN 3:Phép chuyển vị ma trận: Sinh ngẫu nhiên một ma trận có kích thước 3x7. Thực hiện phép chuyển vị đối với ma trận này. Xuất các ma trận này ra màn hình.")
matrix = np.random.rand(3, 7)
matrix_transposition = np.transpose(matrix)

# Xuất giá trị các phần tử của ma trận ra khỏi màn hình
print(f"\nMa trận ban đầu:\n {matrix}")
print(f"Ma trận sau khi chuyển vị:\n {matrix_transposition}")
print("-----------------------------------------------------------------------")
print("\n")


''' 
* \\BÀI TOÁN 4:Phép nhân 2 ma trận:  Am∗n . Bn∗p  =  Cm∗p . Hãy sinh ngẫu nhiên 2 ma trận  A5∗7  và  B7∗3 , tiến hành nhân 2 ma trận này để thu được ma trận  C5∗3 . Xuất các ma trận trên ra màn hình.
Gợi ý: Sử dụng hàm numpy.dot()
* 
* Ý TƯỞNG:
* STEP1: Khởi tạo 2 ma trận matrix_1, matrix_2
* STEP2: Sử dụng cú pháp np.random.rand(3, 7) để khởi tạo 2 ma trận ngẫu nhiên kích thước (3, 7)
* STEP3: Khởi tạo biến matrix_multiplication để lưu giá trị phép nhân ma trận matrix_1 * matrix_2 bằng hàm np.miltiply()
* STEP3: Xuất giá trị ma trận
* 
'''
print("-----------------------------------------------------------------------")
print("BÀI TOÁN 4:Phép nhân 2 ma trận:  Am∗n . Bn∗p  =  Cm∗p . Hãy sinh ngẫu nhiên 2 ma trận  A5∗7  và  B7∗3 , tiến hành nhân 2 ma trận này để thu được ma trận  C5∗3 . Xuất các ma trận trên ra màn hình. Gợi ý: Sử dụng hàm numpy.dot()")
matrix_1 = np.random.rand(5, 7)
matrix_2 = np.random.rand(7, 3)
matrix_multiplication = np.multiply(matrix_1, matrix_2)

# Xuất giá trị các phần tử của ma trận ra khỏi màn hình
print(f"\nMa trận 1:\n {matrix_1}")
print(f"\nMa trận 2:\n {matrix_2}")
print(f"\nMa trận nhân:\n {matrix_multiplication}")
print("-----------------------------------------------------------------------")
print("\n")

''' 
* \\BÀI TOÁN 5: Ma trận khả nghịch: ma trận vuông  An∗m  gọi là khả nghịch (hay không suy biến) nếu tồn tại một ma trận vuông  Bn∗n  sao cho A . B =  In . Khi này, B được gọi là ma trận nghịch đảo của A và ký hiệu là  A−1 . Cho ma trận  A5∗7 , hãy tính ma trận khả nghịch của A.
Gợi ý: Sử dụng hàm numpy.linalg.inv()
* 
* Ý TƯỞNG:
* STEP1: Khởi tạo 1 biến matrix_A (5*7)
* STEP2: Khởi tạo biến matrix_B là ma trận khả nghịch matrx_A thông qua hàm numpy.linalg.inv()
* STEP3: Xuất giá trị ma trận ra màn hình
* 
'''
print("-----------------------------------------------------------------------")
print("BÀI TOÁN 5: Ma trận khả nghịch: ma trận vuông  An∗m  gọi là khả nghịch (hay không suy biến) nếu tồn tại một ma trận vuông  Bn∗n  sao cho A . B =  In . Khi này, B được gọi là ma trận nghịch đảo của A và ký hiệu là  A−1 . Cho ma trận  A5∗7 , hãy tính ma trận khả nghịch của A. Gợi ý: Sử dụng hàm numpy.linalg.inv()")
matrix_A = np.random.rand(5, 5)
matrix_B = np.linalg.inv(matrix_A)

# Xuất giá trị các phần tử của ma trận ra khỏi màn hình
print(f"\nMa trận A:\n {matrix_A}")
print(f"\nMa trận B:\n {matrix_B}")
print("-----------------------------------------------------------------------")
print("\n")

-----------------------------------------------------------------------
BÀI TOÁN 1: Phép cộng ma trận:  Am∗n  +  Bm∗n  =  Cm∗n . Hãy sinh ngẫu nhiên 2 ma trận có kích thước 6x7. Thực hiện phép cộng 2 ma trận trên. Xuất giá trị các ma trận ra màn hình

Ma trận 1:
 [[0.7 0.  0.8 0.2 0.8 0.8 0.1]
 [0.4 0.4 0.7 0.4 0.9 0.1 0.2]
 [0.3 0.1 1.  0.1 0.9 0.2 0.1]
 [0.3 0.7 0.4 0.3 0.2 0.7 0.9]
 [0.7 1.  0.5 0.3 0.1 0.7 0.5]
 [0.1 0.6 0.5 0.4 0.6 0.4 0.1]]
Ma trận 2:
 [[0.8 0.3 0.4 0.5 0.3 0.4 0.5]
 [0.2 1.  0.2 0.9 0.5 1.  0.4]
 [0.7 0.2 0.8 0.1 0.1 0.8 0.9]
 [0.2 0.5 0.4 0.7 0.7 0.9 0.4]
 [0.6 0.9 0.3 0.3 0.8 0.6 0.8]
 [0.1 0.1 0.4 0.4 0.2 0.6 0.2]]
Giá trị tổng của 2 ma trận:
 [[1.5 0.3 1.2 0.8 1.1 1.2 0.6]
 [0.6 1.4 0.9 1.3 1.3 1.  0.6]
 [1.1 0.3 1.7 0.2 1.  0.9 0.9]
 [0.6 1.2 0.9 1.  0.8 1.6 1.3]
 [1.3 1.9 0.8 0.6 0.9 1.3 1.3]
 [0.2 0.8 1.  0.8 0.8 1.1 0.2]]
-----------------------------------------------------------------------


------------------------------------------------------------

ValueError: ignored

**BÀI 9- Vector là dạng ma trận đặc biệt**: Sử dụng numpy để thực hiện các yêu cầu sau:
*   Vector hàng (row vector) thực chất là ma trận có kích thức 1 x *n*. Hãy tạo ngẫu nhiên 1 vector hàng - x có kích thước 1 x 8. Kết quả xuất ra màn hình.
*   Vector cột (column vector) thực chất là ma trận có kích thước *m* x 1. Hãy tạo ngẫu nhiên 1 vector cột - x có kích thước 8 x 1. Kết quả xuất ra màn hình



In [ ]:
'''
*
* Sử dụng thư viện sau:
*
* numpy: Tính toán số học, vector, ma trận.
*
'''
import numpy as np

'''
*
* Cú pháp np.random.rand (d0, d1, …, dn)
* => Chức năng này của mô-đun ngẫu nhiên được sử dụng để tạo ra các số hoặc giá trị ngẫu nhiên trong một hình dạng nhất định.
*
'''

# Tạo ngẫu nhiên 1 vector hàng - x có kích thước 1 x 8
matrix_row = np.random.rand(1, 8)

# Tạo ngẫu nhiên 1 vector cột - x có kích thước 8 x 1
matrix_column = np.random.rand(8, 1)

# Xuất giá trị các phần tử của ma trận ra khỏi màn hình
print(f"\nMa trận hàng:\n {matrix_row}")
print(f"\nMa trận cột:\n {matrix_column}")



Ma trận hàng:
 [[0.2 0.6 0.1 0.2 0.1 0.6 0.2 0.6]]

Ma trận cột:
 [[0.4]
 [0.3]
 [0.8]
 [0.4]
 [0.4]
 [0.1]
 [0.9]
 [0.9]]
